# ============================================================================
# 🚀 Nix Flake Updater Workflow
#
# This workflow keeps your Nix flake.lock up to date, opens a PR, and
# auto-merges it automatically.
#
# REQUIRED REPO SETTINGS:
#   1. Settings → Actions → General → Workflow permissions:
#      "Allow GitHub Actions to create and approve pull requests" ✅
#   2. Settings → General → Pull Requests:
#      "Allow auto-merge" ✅
#
# Troubleshooting:
#   - If you get "not permitted to create pull requests", enable setting #1 above
#   - If auto-merge fails, check repo settings above and token permissions
#   - For best results, enable Dependabot for GitHub Actions updates
# ============================================================================

name: "Update Nix flake.lock"

on:
  schedule:
    # Twice weekly: Mondays & Thursdays at 06:00 UTC
    - cron: '0 6 * * 1,4'
  workflow_dispatch:


concurrency:
  group: update-flake-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # Default, jobs override as needed
  id-token: write # Required for Determinate Nix OIDC
  pull-requests: write # Required for creating PRs
  issues: write # Required for PR assignments

jobs:
  update-and-merge:
    name: "Update flake.lock and auto-merge"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    env:
      NIX_CONFIG: "experimental-features = nix-command flakes"
      NIXPKGS_ALLOW_UNFREE: 1
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v5

      - name: "Install Nix (flakes enabled)"
        # Pinned to major; Dependabot keeps this fresh
        uses: DeterminateSystems/determinate-nix-action@v3
        with:
          extra-conf: |
            experimental-features = nix-command flakes

      - name: "Enable Magic Nix Cache"
        # Pinned to major; Dependabot keeps this fresh
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: "Update flake.lock and open PR with auto-merge"
        uses: DeterminateSystems/update-flake-lock@v27
        with:
          pr-title: "📦 nix flake.lock: update dependencies"
          pr-labels: "dependencies, nix, automated"
          pr-assignees: "kmdtaufik"
          pr-body: |
            ## :rocket: Automated Nix flake.lock update

            This PR updates `flake.lock` to the latest versions and will auto-merge when ready.

            **How to rerun:**
            > Re-run this workflow via GitHub Actions → "Update Nix flake.lock"

            ---
            _Automated PR by [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock)_
          token: ${{ github.token }}
        timeout-minutes: 10

# ============================================================================
# Security & Hygiene:
#   - All third-party actions pinned to major; use Dependabot for updates.
#   - Minimal permissions per job.
#   - Flakes always enabled via NIX_CONFIG.
#   - Timeouts set for long steps.
#
# For more info, see:
#   - https://github.com/DeterminateSystems/determinate-nix-action
#   - https://github.com/DeterminateSystems/magic-nix-cache-action
#   - https://github.com/DeterminateSystems/update-flake-lock
# ============================================================================
